### PR TITLE
Import SRFI 175 sample implementation

### PR DESCRIPTION
**Pull request by lassik**
SRFI 175 (ASCII character library) was just finalized. Here's a copy/paste of the sample implementation. It works as such in Gambit. However the internals can probably be optimized, at least to use fixnum math instead of generic math. The tests should also be converted to use Gambit's test framework; I can do that as an exercise to learn the framework.

### CODE REVIEW

**Comment by lassik** [comment]
Does Gambit guarantee that the maximum character codepoint (i.e. max possible return value of `char->integer`) fits in a fixnum?

**Comment by feeley** [comment]
Yes Gambit implements characters such that the conversion to and from fixnums is always possible:

```
> (fixnum? (char->integer #\x10ffff))  
#t
> (char->integer #\x10ffff)          
1114111
```

**Comment by lassik** [comment]
Nice. Fixnum changes committed in #9.

What's the fastest way to loop over the characters of a (possibly Unicode) string in order? I'm using string ports:

```
       (call-with-port
        (open-input-string x)
        (lambda (in)
          (let check ()
            (let ((char (read-char in)))
              (or (eof-object? char)
                  (and (fx< (char->integer char) #x80) (check)))))))
```

**Comment by feeley** [comment]
That's not ideal because `open-input-string` allocates ~2KB plus a copy of the string.  You could also `(for-each ... (string->list str))` but that allocates too (about 48 bytes per character).  The best (fast and no allocation) is simply a loop with `(string-ref str i)`...

**Comment by lassik** [comment]
Wow, I had no idea a string port allocates that much.

The string looping issue comes up quite often in portable code. `string-ref` is also tricky to get to work fast with Unicode, as character offsets may not be straightforward byte offsets. Does Gambit have some optimization like caching the byte position corresponding to the last `(string-ref s i)` so `(string-ref s (+ i 1))` can be fast?

**Comment by feeley** [comment]
`open-input-string` needs to copy the string because you wouldn't want mutations of the original list to change the content of the port after the port is created.  You also want to chop the string into smaller chunks so that as the string is consumed the GC can get rid of the fully consumed chunks.  For a string port the actual "live" data is closer to ~1KB (the 2KB is the amount allocated for the creation of a string port and it includes garbage).  A string port structure has 44 fields, and contains a mutex (which has 12 fields), and 2 condition variables (which also have 12 fields each).  So that's about `(* (+ 44 12 12 12) 8 2)` = 1280 bytes on a 64 bit machine.  This does not account for the object headers, which are 1 word per object, but it accounts for the factor of 2 "bloat" due to the two space stop-and-copy GC (Gambit considers that when N bytes are allocated in the fromspace, there's in effect also N bytes reserved in the tospace for copying the object, so the total is 2*N bytes allocated).  When the object is large, it is allocated as a still object that does not suffer from the factor of 2 bloat because it is managed by a mark-and-sweep GC.  So if you compare this with other Scheme systems that don't include this factor of 2, the actual overhead for a string port is closer to 600-700 bytes.

Concerning the string representation, Gambit uses a vector of Unicode code points, so character indexing is constant time.  The price to pay is that each character occupies 32 bits.  You can configure Gambit to use 8, 16 or 32 bits per character (but only 32 bits per character supports the full Unicode standard).

**Comment by lassik** [comment]
That is an incredibly good explanation of the pertinent issues. Thanks for taking the time to write it! Might be worth collecting these insights into some kind of Gambit optimization manual.

>  open-input-string needs to copy the string because you wouldn't want mutations of the original list to change the content of the port after the port is created. You also want to chop the string into smaller chunks so that as the string is consumed the GC can get rid of the fully consumed chunks.

This in particular sounds like it makes a great deal of sense.

If strings are 32-bit internally, then string-ref is constant time and hence optimal. I incorrectly assumed they would be UTF-8. The nice thing with 32-bit instead of 16-bit chars is that you don't need to worry about surrogate pairs like JVM Schemes.

**Comment by lassik** [comment]
Since the max Unicode codepoint is less than 2^21, it might be possible to get away with 3-byte chars internally. That would save a byte per character while keeping predictable offsets. I guess address calculations would be slightly slower since 3 is not a power of two, and loads and stores might be slower as well. You've probably considered this approach already.

**Pull request merged**
